# prospector configuration file
doc-warnings: true

inherits:
  - default

pep257:
    disable:
      - D212

ignore-paths:
  - tests

mccabe:
  run: true

dodgy:
  run: true

pep257:
  run: true

pydocstyle:
  run: true

pyflakes:
  run: true

pyroma:
  run: true
