matrix:
  include:
  - os: osx
    language: generic
    osx_image: xcode12.2
    env: MPI_VERSION=OPENMPI
    addons:
      homebrew:
        packages:
          - open-mpi
          - python3
        update: true
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
    before_cache:
      - brew cleanup
  - os: linux
    dist: focal
    language: python
    python: "3.9-dev"
    env: MPI_version=MPICH
    addons:
      apt:
        packages:
          - openmpi-bin
          - libopenmpi-dev
          - python3.9-dev
          - python3.9-venv
  - os: linux
    dist: focal
    language: python
    python: "3.9-dev"
    env: MPI_VERSION=OPENMPI
    addons:
      apt:
        packages:
          - mpich
          - libmpich-dev
          - python3.9-dev
          - python3.9-venv

install:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install .

script:
  - export OMPI_MCA_rmaps_base_oversubscribe=yes
  - pytest tests
